module.exports = {
    alps: require('./alps'),
    b3u1000p: require('./b3u1000p'),
    bat: require('./bat'),
    button: require('./button'),
    choc: require('./choc'),
    choc_kim: require('./choc_kim'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jst_bat: require('./jst_bat'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    nice_view: require('./nice_view'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    pcm12: require('./pcm12'),
    promicro_pretty: require('./promicro_pretty'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    tentingpuck: require('./tentingpuck'),
    trrs: require('./trrs'),
    via: require('./via'),
}